### PR TITLE
feat: content tabs

### LINKED ISSUE #24: Implement a Generic React Component for Weekly Quests, News, and Chests
#### **Description**
We need to create a new generic React component that will display weekly quests, news, and chests. This component should be structured using Shadcn and should include multiple tabs to represent each category. The developer is encouraged to propose a design that they feel is appropriate, as long as it remains visually coherent with the main site. The image given is just to give a guide feel free to explore.

#### **Tasks**
1. **Set Up Component Structure:**
   - Create a new `ContentTabs` component in the `components` directory.
   - Use Shadcn components to ensure the design aligns with our existing UI framework.

2. **Tab Structure:**
   - Implement a tabbed interface within the `ContentTabs` component.
   - Each tab should represent one of the following categories:
     - **Weekly Quests**
     - **News**
     - **Chests**

3. **Weekly Quests Tab:**
   - Create a section to display the current weekly quests.
   - Use appropriate Shadcn components (e.g., cards, lists) to showcase quests.
   - Include relevant details such as quest objectives, rewards, and deadlines.

4. **News Tab:**
   - Create a section to display the latest news.
   - Use Shadcn components to display news items, with support for titles, descriptions, and timestamps.
   - Ensure the news items are easy to update and display in a visually appealing manner.

5. **Chests Tab:**
   - Create a section to display available chests.
   - Use Shadcn components to display chest information, including types, rewards, and availability.
   - Ensure this section is visually consistent with the other tabs.

6. **Design and Customization:**
   - Allow the developer to propose a design that they feel best suits the purpose.
   - Ensure the final design is visually coherent with the main site’s overall design language.
   - Make sure the component is flexible enough for future enhancements or modifications.

7. **Responsive Design:**
   - Ensure the `ContentTabs` component is fully responsive.
   - Test the layout on various screen sizes, including mobile, tablet, and desktop.

8. **Testing:**
   - Write unit tests for the `ContentTabs` component and its sub-components.
   - Ensure that each tab’s functionality, including content display and navigation, is covered in the tests.

9. **Documentation:**
   - Update the project’s documentation to include details about the new `ContentTabs` component.
   - Provide instructions on how to extend or customize the component in the future.

#### **Acceptance Criteria**
- A new `ContentTabs` component exists and integrates seamlessly with the existing app.
- The component includes tabs for Weekly Quests, News, and Chests.
- Each tab displays the relevant content using Shadcn components.
- The developer has the freedom to design the component creatively, as long as it aligns with the main site’s visual style.
- The component is fully responsive and works across different devices.
- All new components and features are fully tested and documented.

GameBoard - 2

### PR DESCRIPTION
**Pull request by Oshioke-Salaki**
fixes #24
Feat: Content Tabs

## Summary by CodeRabbit

- **New Features**
	- Introduced a new `ContentTabs` component for improved content organization, allowing users to easily navigate between "Weekly Quests," "News," and "Chests."
	- Added `ChestCard`, `NewsCard`, `QuestCard`, and `WeeklyQuests` components to enhance the display of chests, news articles, and quests.
	- Enhanced the user interface with the addition of the `shadcn-ui` library for better styling and component options.

- **Improvements**
	- Implemented a responsive design using Tailwind CSS, ensuring an engaging and visually appealing user experience.

### CODE REVIEW

**Comment by Cheelax** [comment]
hi @Oshioke-Salaki 
Some little points:
- I see there is a conflict to solve
- can you send a screen of the component where it's supposed to be?

**Comment by Oshioke-Salaki** [comment]
> hi @Oshioke-Salaki Some little points:
> 
> * I see there is a conflict to solve
> * can you send a screen of the component where it's supposed to be?

Done
I just places it in the home screen for now. So you can review it

**Comment by Cheelax** [comment]
> > hi @Oshioke-Salaki Some little points:
> > 
> > * I see there is a conflict to solve
> > * can you send a screen of the component where it's supposed to be?
> 
> Done I just places it in the home screen for now. So you can review it

Can you send some screenshots here?

**Comment by Oshioke-Salaki** [comment]
Screenshot 2024-08-29 at 14 35 42
Screenshot 2024-08-29 at 14 35 51
Screenshot 2024-08-29 at 14 36 00

**Comment by Cheelax** [comment]
Thank you.
For what I see, we miss the logic of showing and hidding this component right?

**Comment by Oshioke-Salaki** [comment]
Yes we are. So I just passed dummy data as props for now.

**Comment by Cheelax** [comment]
This PR can be merged only if we manage when to view and not to view the modal

**Comment by Oshioke-Salaki** [comment]
Okay should I create a button in the home page to control it? Will that be enough to merge?

**Comment by Cheelax** [comment]
Maybe a button in the header is enough.
We need to be able to close it too

**Pull request closed without merging**
